version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies
      - npm install

  build:
    commands:
      - echo Building React app
      - npm run build

  post_build:
    commands:
      - echo Invalidating CloudFront cache
      - aws cloudfront create-invalidation --distribution-id E3DEW3Q135TWN0 --paths "/*"

artifacts:
  files:
    - '**/*'
  base-directory: dist